name: Gatsby Publish

on:
  push:
    branches: master
  release:
    types:
      - released

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      GATSBY_PATH_PREFIX: "/gatsby-contentful"
      GATSBY_PUBLIC_URL: "https://rcbgdf.github.io/gatsby-contentful"
#      GATSBY_PUBLIC_URL: "https://rc-bgdf.de"
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "GATSBY_RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Node installieren & Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: package.json
      - run: |
          env
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config user.name toastmaster
          git config user.email toastmaster@rc-bgdf.de
          git config --list
          npm i
          npm run clean
          npm run deploy
          tree public

      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public

